# reset the starting index
set -g base-index 1

# set vi mode
set -g status-keys vi
setw -g mode-keys vi

# split pane bindings
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# better pane navigation
bind C-h select-pane -L
bind C-l select-pane -R
bind C-j select-pane -D
bind C-k select-pane -U

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
